# Création de la première base de données #

In [7]:
import pandas as pd
df = pd.read_csv('result_trie.csv')
df_naf = pd.read_csv('output_icpe_with_NAF.csv')
df_naf.rename(columns={'entete_nom': 'Nom',
                   'entete_siret': 'Siret',
                   'situation_administrative_code_rubrique': 'Code_Rubrique',
                   'entete_statut_seveso': 'Statut_Seveso',
                   'situation_administrative_libelle_rubrique': 'Libelle_rubrique',
                   'situation_administrative_volume' : 'Volume'}, inplace=True)
df_naf = df_naf.drop(columns=['entete_etat_d_activite', 'entete_regime_en_vigueur_de_l_etablissement_2', 
                                            'entete_ied_-_mtd', 'situation_administrative_alinea'])

/var/folders/_l/z5vqwjnn06l67wbqpt8pt73c0000gn/T/ipykernel_11702/2296589397.py:2: DtypeWarning: Columns (0: cd_insee, 1: cd_postal) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('result_trie.csv')

In [8]:
# Nettoyage du csv pour faire un merge plus propre ultérieurement
df.rename(columns={'code_aiot': 'num_etablissement'}, inplace=True)
print(df.columns)

Index(['num_etablissement', 'nom_ets', 'x', 'y', 'adresse', 'cd_insee',
       'cd_postal', 'commune', 'code_naf', 'lib_naf', 'num_siret', 'cd_regime',
       'lib_regime', 'seveso', 'lib_seveso', 'Description du code ICPE',
       'ICPE_A', 'ICPE_E', 'ICPE_D', 'date_modification',
       'derniere_inspection'],
      dtype='str')

In [ ]:
df.drop(columns=['x', 'y', 'date_modification', 'seveso', 'lib_seveso','date_modification', 'cd_insee'], inplace=True)
print(df.columns)
df = df[['nom_ets','num_etablissement', 'adresse', 'cd_postal', 'commune',
       'code_naf', 'lib_naf', 'num_siret', 'cd_regime', 'lib_regime',
       'Description du code ICPE', 'ICPE_A', 'ICPE_E', 'ICPE_D',
       'derniere_inspection']]

Index(['num_etablissement', 'nom_ets', 'adresse', 'cd_postal', 'commune',
       'code_naf', 'lib_naf', 'num_siret', 'cd_regime', 'lib_regime',
       'Description du code ICPE', 'ICPE_A', 'ICPE_E', 'ICPE_D',
       'derniere_inspection'],
      dtype='str')

In [10]:
df_naf.head()

,num_etablissement,Nom,Siret,Statut_Seveso,derniere_date_inspection,Code_Rubrique,Libelle_rubrique,situation_administrative_regime_autorise,Volume,code_naf,nomenclatureActivitePrincipaleEtablissement,coordonneeLambertAbscisseEtablissement,coordonneeLambertOrdonneeEtablissement
0,39,COLLECTES VALORISATION ENERGIE DECHETS - COVED,3.434035e+13,Non Seveso,2026-01-26,2782,Autres traitements biologiques de déchets non ...,Autorisation,NaN,38.32Z,NAFRev2,NaN,NaN
1,39,COLLECTES VALORISATION ENERGIE DECHETS - COVED,3.434035e+13,Non Seveso,2026-01-26,3532,Valorisation de déchets non dangereux,Autorisation,518.000 t/j,38.32Z,NAFRev2,NaN,NaN
2,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,Non Seveso,NaN,1436,Liquides combustibles de point éclair compris ...,Déclaration avec contrôle,900.000 t,41.10A,NAFRev2,651515.228071,6.863555e+06
3,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,Non Seveso,NaN,1450,Solides inflammables,Autorisation,150.000 t,41.10A,NAFRev2,651515.228071,6.863555e+06
4,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,Non Seveso,NaN,1510,Entrepôts couverts soumis à EE systématique,Autorisation,NaN,41.10A,NAFRev2,651515.228071,6.863555e+06

# Organisation de la deuxième base de données #

In [11]:
df2 = pd.read_csv("output_icpe_with_NAF.csv", dtype={'entete_siret': str})
df2.head()

,num_etablissement,entete_nom,entete_siret,entete_etat_d_activite,entete_regime_en_vigueur_de_l_etablissement_2,entete_statut_seveso,entete_ied_-_mtd,derniere_date_inspection,situation_administrative_code_rubrique,situation_administrative_alinea,situation_administrative_libelle_rubrique,situation_administrative_regime_autorise,situation_administrative_volume,code_naf,nomenclatureActivitePrincipaleEtablissement,coordonneeLambertAbscisseEtablissement,coordonneeLambertOrdonneeEtablissement
0,39,COLLECTES VALORISATION ENERGIE DECHETS - COVED,34340353103542,En exploitation avec titre,Autorisation,Non Seveso,Oui,2026-01-26,2782,NaN,Autres traitements biologiques de déchets non ...,Autorisation,NaN,38.32Z,NAFRev2,NaN,NaN
1,39,COLLECTES VALORISATION ENERGIE DECHETS - COVED,34340353103542,En exploitation avec titre,Autorisation,Non Seveso,Oui,2026-01-26,3532,NaN,Valorisation de déchets non dangereux,Autorisation,518.000 t/j,38.32Z,NAFRev2,NaN,NaN
2,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,42298971500186,En exploitation avec titre,Autorisation,Non Seveso,Non,NaN,1436,2,Liquides combustibles de point éclair compris ...,Déclaration avec contrôle,900.000 t,41.10A,NAFRev2,651515.228071,6.863555e+06
3,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,42298971500186,En exploitation avec titre,Autorisation,Non Seveso,Non,NaN,1450,1,Solides inflammables,Autorisation,150.000 t,41.10A,NAFRev2,651515.228071,6.863555e+06
4,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,42298971500186,En exploitation avec titre,Autorisation,Non Seveso,Non,NaN,1510,1,Entrepôts couverts soumis à EE systématique,Autorisation,NaN,41.10A,NAFRev2,651515.228071,6.863555e+06